version: '3.4'

volumes:
  postgres_data:
      driver: local

services:
  keycloak_postgres:
      container_name: keycloak_postgres
      image: postgres
      volumes:
       - postgres:/data/postgres
      environment:
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: keycloak
        PGDATA: /data/postgres
      ports:
       - 5433:5432
      networks:
       - keycloak
      restart: unless-stopped
    
  keycloak:
      container_name: keycloak_gymly
      image: keycloak_gymly
      environment:
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: admin
      ports:
        - 8443:8443
      depends_on:
        - keycloak_postgres
      networks:
        - keycloak
      volumes:
        - ./certs:/etc/x509/https
        
networks: 
  keycloak:
    driver: bridge

volumes:
  postgres: